[build]
builder = "nixpacks"
buildCommand = "./build.sh"

[deploy]
startCommand = ". /opt/venv/bin/activate && uvicorn api:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"
